### ISSUE TITLE
Tabular checklist

### ISSUE THREAD

**Issue by Dufran** [HomeLabHQ/checklist-manager#8]
- [ ] Create a separate type of checklist
- [ ] Add table checklist CRUD
- [ ] Add relevant properties
